# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-openstack-provider'

$script = <<SCRIPT
# prep env and git clone
sudo apt-get update 
sudo apt-get install -y git vim 
git clone https://github.com/openstack-dev/devstack.git devstack
cd devstack
git checkout stable/kilo
# Build DevStack
sudo cp samples/local.conf .
sudo chown -R ubuntu ../devstack
sudo su ubuntu -c "./stack.sh"

# K2K federation 

SCRIPT

Vagrant.configure(2) do |config|
  # define instances in loop
  config.hostmanager.enabled = true
  #config.hostmanager.manage_host = true  # Annoyingly ask for pw

  config.vm.define "k2k-sp" do |devstack|
    devstack.ssh.username = 'ubuntu'
    # change to your own private key
    devstack.ssh.private_key_path = ''

    # define os instance
    devstack.vm.provider :openstack do |os|
      os.openstack_auth_url   = ''   
      os.username             = ENV['OS_USERNAME']
      os.password             = ENV['OS_PASSWORD']
      os.tenant_name          = ENV['OS_TENANT_NAME']
      os.flavor               = ''
      os.server_name          = "k2k-sp"
      os.image                = ''
      os.endpoint_type        = 'publicURL'
      # name of public key corresponding to ur private key on os project
      os.sync_method          = 'rsync'
      os.keypair_name         = '' 
    end

    devstack.vm.provision "shell", inline: <<-SHELL
      cat /dev/null > /etc/hosts
    SHELL

    devstack.vm.hostname = "k2k-sp"
    devstack.vm.provision :hostmanager

    # shell command to update vm and install devstack
    devstack.vm.provision "shell", inline: $script

    devstack.vm.synced_folder "../auto-IdP", "/home/ubuntu/IdP"
    devstack.vm.synced_folder "../auto-SP", "/home/ubuntu/SP"
 end

  config.vm.define "k2k-idp" do |devstack|
    devstack.ssh.username = 'ubuntu'
    # change to your own private key
    devstack.ssh.private_key_path = ''

    # define os instance
    devstack.vm.provider :openstack do |os|
      os.openstack_auth_url   = ''   
      os.username             = ENV['OS_USERNAME']
      os.password             = ENV['OS_PASSWORD']
      os.tenant_name          = ENV['OS_TENANT_NAME']
      os.flavor               = ''
      os.server_name          = "k2k-idp"
      os.image                = ''
      os.endpoint_type        = 'publicURL'
      # name of public key corresponding to ur private key on os project
      os.sync_method          = 'rsync'
      os.keypair_name         = '' 
    end

    devstack.vm.provision "shell", inline: <<-SHELL
      cat /dev/null > /etc/hosts
    SHELL

    devstack.vm.hostname = "k2k-idp"
    devstack.vm.provision :hostmanager

    # shell command to update vm and install devstack
    devstack.vm.provision "shell", inline: $script

    devstack.vm.synced_folder "../auto-IdP", "/home/ubuntu/IdP"
    devstack.vm.synced_folder "../auto-SP", "/home/ubuntu/SP"
  end
end
